name: Deploy on push to master
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to VPs via SSH
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_IP }}
                    username: ${{ secrets.SERVER_USER }}
                    key: ${{ secrets.SERVER_SSH_KEY }}
                    script: |
                        export NVM_DIR="$HOME/.nvm"
                        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                        cd /root/Gad/web/Apps/xmanager
                        git fetch origin
                        git reset --hard origin/main
                        pnpm exec prisma migrate deploy
                        ./scripts/deploy.sh

